services:
    mysql:
        container_name: mysql
        image: 'mysql:8.0'
        restart: always
        ports:
            - '127.0.0.1:3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'dbuser'
            MYSQL_PASSWORD: 'dbpassword'
        volumes:
            - ./mysql:/var/lib/mysql

    phpmyadmin:
        container_name: phpmyadmin
        image: 'phpmyadmin/phpmyadmin'
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        ports:
            - '127.0.0.1:8085:80'

    app:
        build:
            context: ./app/
            dockerfile: Dockerfile
        container_name: app
        restart: always
        ports:
            - "127.0.0.1:8082:80"
        volumes:
            - ./app/default.conf:/etc/nginx/conf.d/default.conf
            - ./app/nginx.conf:/etc/nginx/nginx.conf
            - ./app/php.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./app/www:/var/www/html
        healthcheck:
          test: curl --fail http://localhost/ping || killall nginx
          interval: 10s
          timeout: 3s
          retries: 2
          start_period: 10s
